project:
  type: website

website:
  title: "0122VAA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
      - text: inclass 
        menu: 
          - text: in-class ex03
          - href: inclass03/inclass03.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


